@startuml
class Item.HealthThing {
}
class Item.Item {
- ArrayList<BaseItem> inventory
+ void addItem(BaseItem)
+ ArrayList<BaseItem> getInventory()
}


class Screen.UI.ScreenManager {
- Stage stage
+ void showTitle()
+ void showChoose()
+ void endGame()
+ void showGame()
+ Stage getStage()
+ void setStage(Stage)
+ void showHowToPlay()
+ void showResult()
}


class Screen.BuildingScreen.Park.Park {
+ void interact(GamePaneImage)
}

class Screen.BuildingScreen.Dome.DomePopup {
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Dome.DomeAction {
+  SLEEP
+  RELAX
- String name
- int price
- String color
- int staminaCost
- int happinessGain
+ String getName()
+ int getPrice()
+ String getColor()
+ void execute(GamePaneImage)
}


interface Screen.BuildingScreen.Shopable {
~ Button createShopButton(ShopItem,GamePaneImage,Runnable)
}

class Screen.HowToPlay.HowToPlayScreen {
- VBox createSection(String,String,String)
}

class Screen.BuildingScreen.Travel.TravelPopup {
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Travel.Destination {
+  BEACH
+  JAPAN
+  PARIS
- String name
- int price
- String color
- int staminaCost
- int happinessGain
+ String getName()
+ int getPrice()
+ String getColor()
+ void execute(GamePaneImage)
}


class Character.Nerd {
- int studyCount
+ String earnStudyBonus()
}


class Screen.BuildingScreen.Mall.MallPopup {
+ {static} void resetAllMallItems()
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Mall.MallItem {
+  PILLOW
+  TUNG_BED
+  CAR
- String name
- int price
- String color
- int healthGain
- boolean isUnique
- boolean soldOut
+ String getName()
+ int getPrice()
+ String getColor()
+ {static} void resetMallItems()
+ void execute(GamePaneImage)
}


class Screen.BuildingScreen.Gym.GymPopup {
+ {static} void resetAllGymService()
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Gym.GymService {
+  WORKOUT
+  POWER
+  BEAST
+  PROTEIN
- String name
- int price
- String color
- int staminaCost
- int healthGain
- boolean isUnique
- boolean isSoldOut
+ String getName()
+ int getPrice()
+ String getColor()
+ {static} void resetGymService()
+ void execute(GamePaneImage)
}


abstract class Character.BasePlayer {
- CharacterType characterType
- int stamina
- int money
- int education
- int health
- int happiness
- int healthDecrease
- int staminaDecrease
- CharacterType type
- String imagePath
- Item itemManager
- Image imgDown
- Image imgLeft
- Image imgRight
- Image imgUp
- int maxUnlockedLevel
+ void walk()
+ int getStamina()
+ void setStamina(int)
+ int getStaminaDecrease()
+ void setStaminaDecrease(int)
+ int getMoney()
+ void setMoney(int)
+ int getEducation()
+ void setEducation(int)
+ int getHealth()
+ void setHealth(int)
+ int getHealthDecrease()
+ void setHealthDecrease(int)
+ int getHappiness()
+ void setHappiness(int)
+ CharacterType getType()
+ void setType(CharacterType)
+ String getImagePath()
+ void setImagePath(String)
+ Item getItemManager()
+ int getMaxUnlockedLevel()
+ void setMaxUnlockedLevel(int)
+ Image getImgDown()
+ void setImgDown(Image)
+ Image getImgLeft()
+ void setImgLeft(Image)
+ Image getImgRight()
+ void setImgRight(Image)
+ Image getImgUp()
+ void setImgUp(Image)
+ boolean work(int,int)
+ String study(int,int)
}


class Screen.BuildingScreen.Restaurant.RestaurantPopup {
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Restaurant.FoodMenu {
+  PAD_THAI
+  KRAPAO
+  TOM_YUM
- String name
- int price
- String color
- int staminaGain
- int healthGain
+ String getName()
+ int getPrice()
+ String getColor()
+ void execute(GamePaneImage)
}


class Logic.GameSession {
- {static} BasePlayer player
- {static} int MAX_ROUNDS
- {static} int round
- {static} int initialStamina
+ {static} void setBasePlayer(BasePlayer)
+ {static} BasePlayer getPlayer()
+ {static} int getRound()
+ {static} int getMaxRounds()
+ {static} int getInitialStamina()
+ {static} void advanceRound()
+ {static} boolean isLastRound()
}


interface Screen.BuildingScreen.ShopItem {
~ String getName()
~ int getPrice()
~ String getColor()
~ void execute(GamePaneImage)
}

class Item.Vehicle {
}
class Screen.BuildingScreen.Park.ParkPopup {
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Park.ParkAction {
+  WALK
+  RELAX
- String name
- int price
- String color
- int staminaCost
- int happinessGain
- int healthGain
+ String getName()
+ int getPrice()
+ String getColor()
+ void execute(GamePaneImage)
}


class Screen.BuildingScreen.Dome.Dome {
+ void interact(GamePaneImage)
}

class Screen.BuildingScreen.Chula.Chula {
+ void interact(GamePaneImage)
}

abstract class Screen.BuildingScreen.Building {
# String name
+ {abstract}void interact(GamePaneImage)
}


class Item.WheyProtein {
}
class Character.Otaku {
- int workCount
+ String earnWorkBonus()
}


class Character.NormalGuy {
}
class Screen.UI.ToastUtil {
- {static} Stage currentToastStage
- {static} javafx.animation.FadeTransition currentFade
+ {static} void showToast(String,String,double,double,boolean)
}


class Item.Book3 {
}
class Character.PlayerCreate {
+ {static} BasePlayer create(CharacterType)
}

class Screen.Choosing.ChoosingScreen {
- String[] avatarPaths
- String[] archetypeNames
- String[] prosCons
- int selectedIndex
- Label selectedTitle
- Label selectedDesc
- void refreshDescription()
- String cardStyle(boolean)
- ImageView safeAvatar(String)
}


class Item.EducationThing {
}
class Screen.BuildingScreen.Gym.Gym {
+ void interact(GamePaneImage)
}

class Screen.BuildingScreen.Travel.Travel {
+ void interact(GamePaneImage)
}

class Screen.Game.StatusTab {
- ProgressBar staminaBar
- Label staminaLabel
- ImageView[] itemSlots
- StackPane createAvatarSection()
- VBox createBar(String,String)
+ void updateStatus()
- void updateInventoryDisplay(Item)
- void animateBar(ProgressBar,double)
}


class Item.Book2 {
}
class Screen.Game.Gamebar {
- Button go_back
- Button end_round
- Button action
- Button musicToggle
- Label roundLabel
+ void updateRound(int,int)
+ Button getGo_back()
+ Button getEnd_round()
+ Button getAction()
+ void setActionVisible(boolean)
+ void setOnActionClick(Runnable)
}


class Main.main {
+ void start(Stage)
+ {static} void main(String[])
}

class Screen.Result.ResultScreen {
- String[] Badge
- {static} int MONEY_SSTAR
- {static} int MONEY_S
- {static} int HEALTH_SSTAR
- {static} int HEALTH_S
- {static} int EDUCATION_SSTAR
- {static} int EDUCATION_S
- {static} int HAPPINESS_SSTAR
- {static} int HAPPINESS_S
- HBox createStatusRow(String,int)
- ImageView createBadge(String,int)
}


enum Character.CharacterType {
+  GYMBRO
+  NERD
+  OTAKU
+  NORMAL
}

class Screen.UI.UIUtil {
- {static} Font pixelFont
+ {static} Font getPixelFont(double)
}


enum Item.Category {
+  EDUCATION
+  HEALTH
+  VEHICLE
+ String[] value()
+ Class<? extends Annotation> annotationType()
}


class Screen.UI.TitleScreen {
- ScreenManager begin
- Text title
- Button start
- Button how_to_play
- Button exit
- Button createPixelButton(String)
}


class Item.BaseItem {
- String name
- String image
- boolean active
- Category category
+ String getName()
+ void setName(String)
+ String getImage()
+ void setImage(String)
+ boolean isActive()
+ void setActive(boolean)
+ Category getCategory()
+ void setCategory(Category)
}


class Screen.Game.GameScreen {
- void handleEndRound(ScreenManager,Gamebar,GamePaneImage,StatusTab)
}

class Screen.BuildingScreen.Restaurant.Restaurant {
+ void interact(GamePaneImage)
}

class Logic.GamePaneImage {
- MapCreate MapCreate
- int TILE_SIZE
- boolean[][] clickable
- Image imgDown
- Image imgLeft
- Image imgRight
- Image imgUp
- BasePlayer playerType
- Runnable onReachBuilding
- Runnable onLeaveBuilding
- Runnable onStatusChange
- int playerRow
- int playerCol
- ImageView playerImage
- boolean isMoving
- Building[][] bmap
- int[][] map
- void drawMap()
- List<int[]> findPath(int,int,int,int)
- void clickablePath()
- void walkPath(List<int[]>)
+ boolean CheckPlayer()
+ void resetPlayerToStart()
+ boolean isPlayerMoving()
+ void addItem(String)
+ void updateEducationItem(int)
- void updatePlayerPosition()
+ Building getCurrentBuilding()
+ void setImgDown()
+ void notifyUpdate()
+ void setOnReachBuilding(Runnable)
+ void setOnLeaveBuilding(Runnable)
+ void setOnStatusChange(Runnable)
+ void setImgLeft()
+ void setImgRight()
+ void setImgUp()
+ BasePlayer getPlayerImage()
}


class Screen.BuildingScreen.Mall.Mall {
+ void interact(GamePaneImage)
}

class Audio.SoundManager {
- {static} MediaPlayer backgroundPlayer
- {static} boolean muted
+ {static} void playBackground(String)
+ {static} void stopBackground()
+ {static} void toggleMute()
+ {static} boolean isMuted()
}


class Item.Book4 {
}
class Item.Book1 {
}
class Screen.BuildingScreen.Chula.ChulaPopup {
+ {static} void show(GamePaneImage)
}

enum Screen.BuildingScreen.Chula.StudyLevel {
+  HIGH_SCHOOL
+  BACHELOR
+  MASTER
+  DOCTORATE
- String name
- int price
- String color
- int eduGain
- int levelIndex
+ String getName()
+ int getPrice()
+ String getColor()
+ void execute(GamePaneImage)
}


class Logic.MapCreate {
- ImageView choosing
- Image wallImage
- Image streetImage90
- Image streetImage180
- Image floorImage
- Image domeleft
- Image domeright
- Image gymTop
- Image gymMid
- Image gymBot
- Image Uni1
- Image Uni2
- Image resLeft
- Image resRight
- Image traveLeft
- Image traveRight
- Image parkLeft
- Image parkRight
- Image mallTop
- Image mallMid
- Image mallBot
- Image water
- Image watertop
- Image flower
+ ImageView getChoosing()
}


interface Screen.BuildingScreen.Normal {
~ BorderPane createBaseLayout(Stage,GamePaneImage,String,Color,String,String,Runnable,Runnable,Label)
- String toHex(Color)
~ void applyPixelStyle(Button,String)
}

class Character.GymBro {
- int workCount
+ String earnWorkBonus()
}




Item.BaseItem <|-- Item.HealthThing
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Park.Park
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Dome.DomePopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Dome.DomePopup
Screen.BuildingScreen.Normal <|-- Screen.BuildingScreen.Shopable
Screen.HowToPlay.BorderPane <|-- Screen.HowToPlay.HowToPlayScreen
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Travel.TravelPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Travel.TravelPopup
Character.BasePlayer <|-- Character.Nerd
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Mall.MallPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Mall.MallPopup
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Gym.GymPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Gym.GymPopup
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Restaurant.RestaurantPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Restaurant.RestaurantPopup
Item.BaseItem <|-- Item.Vehicle
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Park.ParkPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Park.ParkPopup
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Dome.Dome
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Chula.Chula
Item.HealthThing <|-- Item.WheyProtein
Character.BasePlayer <|-- Character.Otaku
Character.BasePlayer <|-- Character.NormalGuy
Item.EducationThing <|-- Item.Book3
javafx.scene.layout.BorderPane <|-- Screen.Choosing.ChoosingScreen
Item.BaseItem <|-- Item.EducationThing
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Gym.Gym
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Travel.Travel
Screen.Game.VBox <|-- Screen.Game.StatusTab
Item.EducationThing <|-- Item.Book2
javafx.scene.layout.BorderPane <|-- Screen.Game.Gamebar
javafx.application.Application <|-- Main.main
Screen.Result.StackPane <|-- Screen.Result.ResultScreen
Screen.UI.VBox <|-- Screen.UI.TitleScreen
Screen.Game.VBox <|-- Screen.Game.GameScreen
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Restaurant.Restaurant
javafx.scene.layout.Pane <|-- Logic.GamePaneImage
Screen.BuildingScreen.Building <|-- Screen.BuildingScreen.Mall.Mall
Item.EducationThing <|-- Item.Book4
Item.EducationThing <|-- Item.Book1
Screen.BuildingScreen.Shopable <|.. Screen.BuildingScreen.Chula.ChulaPopup
Screen.BuildingScreen.Normal <|.. Screen.BuildingScreen.Chula.ChulaPopup
Character.BasePlayer <|-- Character.GymBro
@enduml